phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Building documaid
      - mvn clean install -DskipTests
      - VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
      - echo Running documaid generate goal
      - mvn de.quantummaid:documaid:$VERSION:validate -DskipPaths=docs/Usage.md