version: 0.2

env:
  parameter-store:
    SETTINGSXML: /Quantummaid/CI/sonatype/settingsxml
    PGPSIGNKEY_1: /Quantummaid/CI/signPrivateKey/1
    PGPSIGNKEY_2: /Quantummaid/CI/signPrivateKey/2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "${SETTINGSXML}" >> ~/.m2/settings.xml
      - echo "${PGPSIGNKEY_1}${PGPSIGNKEY_2}" | gpg --import
  build:
    commands:
      - echo "Building documaid"
      - mvn clean install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
      - echo "Running documaid validate goal"
      - mvn de.quantummaid:documaid:$VERSION:validate -DskipPaths=docs/Usage.md
      - mvn -B deploy
