version: 0.2

env:
  parameter-store:
    SETTINGSXML: /Quantummaid/CI/sonatype/settingsxml

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - whoami
      - ls -laR /home/
      - mkdir ~/.m2
      - gpg --version || echo "gpg not found"
      - gpg2 --version || echo "gpg2 not found"
      - echo "${SETTINGSXML}" >> ~/.m2/settings.xml
  build:
    commands:
      - whoami
      - ls -laR /home/
      - echo Building documaid
      - mvn clean install -DskipTests
      - VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
      - echo Running documaid generate goal
      - mvn de.quantummaid:documaid:$VERSION:validate -DskipPaths=docs/Usage.md
